# Generated by Django 4.1.5 on 2023-01-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('To do', 'Todo'), ('Doing', 'Doing'), ('Done', 'Done')], default='To do', max_length=100)),
            ],
        ),
    ]
